export const catsImagesUrl = [
  { id: 1, url: "https://cdn2.thecatapi.com/images/1se.jpg" },
  { id: 2, url: "https://cdn2.thecatapi.com/images/26c.jpg" },
  {
    id: 3,
    url: "https://30.media.tumblr.com/tumblr_krvxbfFEsf1qa9hjso1_1280.png",
  },
  { id: 4, url: "https://cdn2.thecatapi.com/images/5gu.jpg" },
  { id: 5, url: "https://cdn2.thecatapi.com/images/5jm.jpg" },
  { id: 6, url: "https://cdn2.thecatapi.com/images/751.jpg" },
  { id: 7, url: "https://cdn2.thecatapi.com/images/8ve.jpg" },
  { id: 8, url: "https://cdn2.thecatapi.com/images/a7o.jpg" },
  { id: 9, url: "https://cdn2.thecatapi.com/images/dq2.jpg" },
  { id: 10, url: "https://cdn2.thecatapi.com/images/dt5.jpg" },
  { id: 11, url: "https://cdn2.thecatapi.com/images/MTU2Mjk2NA.jpg" },
  { id: 12, url: "https://cdn2.thecatapi.com/images/MTgyMDcwNA.jpg" },
  { id: 13, url: "https://cdn2.thecatapi.com/images/MTg2Mzk0Mg.jpg" },
  { id: 14, url: "https://cdn2.thecatapi.com/images/hBXicehMA.jpg" },
  { id: 15, url: "https://cdn2.thecatapi.com/images/RhBsBQg6y.jpg" },
  { id: 16, url: "https://cdn2.thecatapi.com/images/267.jpg" },
  { id: 17, url: "https://cdn2.thecatapi.com/images/2mh.jpg" },
  { id: 18, url: "https://cdn2.thecatapi.com/images/94n.jpg" },
  { id: 19, url: "https://cdn2.thecatapi.com/images/9pk.jpg" },
  { id: 20, url: "https://cdn2.thecatapi.com/images/b0u.jpg" },
  { id: 21, url: "https://cdn2.thecatapi.com/images/bc0.jpg" },
  { id: 22, url: "https://cdn2.thecatapi.com/images/e14.jpg" },
  { id: 23, url: "https://cdn2.thecatapi.com/images/MTY3MTcwMg.jpg" },
  { id: 24, url: "https://cdn2.thecatapi.com/images/MTkyNTIwMA.jpg" },
];
